# Generated by Django 3.0.8 on 2020-08-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200801_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
