# Generated by Django 3.0.8 on 2020-08-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.CharField(choices=[('done', 'done'), ('in process', 'in process')], max_length=20),
        ),
    ]
