# Generated by Django 3.0.8 on 2020-08-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200801_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
